### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by geocine** [jiongxuan/deapk#1]
Hi I tried two different apk files and I always get stuck at step 3/5 with this error. I am on Windows 7x64. I downloaded 1.5 tag and exported a runnable jar on eclipse and here is what I got.

```
>>> Starting Deapk now!(1/1)
    This may take a few seconds to complete.

>>> (1/5) Decompiling all resource files and smali files...
>>> (2/5) Extracting files...
>>> (3/5) Generating all Java Class files...Exception in thread "main" java.lang
.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.closeQuiet
ly(Ljava/io/InputStream;)V
        at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:17
66)
        at com.googlecode.dex2jar.reader.DexFileReader.<init>(DexFileReader.java
:240)
        at i.am.jiongxuan.deapk.Deapk.decodeToClassDex(Deapk.java:178)
        at i.am.jiongxuan.deapk.Deapk.start(Deapk.java:122)
        at i.am.jiongxuan.deapk.MainApplication.deapkNow(MainApplication.java:13
3)
        at i.am.jiongxuan.deapk.MainApplication.main(MainApplication.java:73)
        ... 5 more
```

**Comment by jiongxuan** [comment]
Thanks a million! 

I've already fixed in v2.0. Please checkout and try again!
